#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Regenerate the mcm-abstract RED-stage **inputs** from the corpus, byte-for-byte.

What this script produces
-------------------------
Seven files, all under `--out` (default: a fresh temp dir):

    case-A-problem.txt         官方题面 (2025 MCM Problem A), pdftotext 抽取
    case-C-problem.txt         官方题面 (2025 MCM Problem C), pdftotext -layout 抽取
    case-A-body.md             O 奖论文正文（已剥页面残渣；含 Task 1 与 Task 2 的结果）
    case-C-body.md             同上，C 题
    case-A-true-abstract.md    论文自己的 Summary 段（"真摘要"，用于对照）
    case-C-true-abstract.md    同上，C 题
    case-A-body-partial.md     *人为削过* 的 case-A-body.md：Task 2 的结果被删掉
                               （判据/方法/公式保留）。它是合成输入，不是任何真实论文的样子。

**These are the INPUTS only.**  The RED-stage OUTPUTS — `red-A1.md`, `red-A2.md`,
`red-C1.md`, `red-A3-partial.md`, `red-P1.md`, `red-P2.md` — are **agent samples and are
NOT produced by this script and cannot be regenerated by any script.**  They live in the
repo (`tests/skills/abs-cases/red/`) purely so that they are not lost; this script only
ever reads them, and only to compare nothing (it does not touch them).

Sources (sha256-pinned; the script refuses to run if they changed)
-------------------------------------------------------------------
    corpus/papers/md/2025美赛O奖论文/A/2501909.md      2025 MCM Problem A, O 奖论文
    corpus/papers/md/2025美赛O奖论文/C/2505964.md      2025 MCM Problem C, O 奖论文
    corpus/官方原题/2025/2025_MCM_Problem_A.pdf        官方题面
    corpus/官方原题/2025/2025_MCM_Problem_C.pdf        官方题面

Transformation rules
--------------------
`problem.txt` — `pdftotext -enc UTF-8` (A) / `pdftotext -enc UTF-8 -layout` (C), raw
output, no post-processing (CRLF and the trailing form feed are kept as emitted).

`body.md` / `true-abstract.md` — derived from the corpus `.md` by, in order:

  1. drop U+0000 (the C corpus carries one stray NUL byte; the artifact does not);
  2. drop the front-matter ranges listed in CUTS below;
  3. drop page-residue lines: `^<!-- page N -->$`, `^Team # N$`, `^Page N of M$`;
  4. collapse every run of 3+ blank lines down to 2;
  5. drop trailing blank lines and end the file with exactly one `\\n`.

  `true-abstract.md` = `"Summary\\n"` + corpus lines `ABSTRACT[letter]` + `"\\n"`.
  `body-partial.md`  = the cut list in PARTIAL_CUTS applied to the *generated* body.md
  (ported verbatim from the throwaway `build/abs-red/make_partial.py`).

Honest note on step 2 — the cuts were NOT recorded anywhere
-----------------------------------------------------------
The task brief said the rules were "已记录 in build/abs-red/compile-report.md".  **They are
not.**  `compile-report.md` is a *measurement* report (it documents how the three baseline
abstracts behaved inside the COMAP template); it contains no generation rules, and it does
not even mention the `red-*.md` artifacts.  There is no `measure-pdf.md` at all.  Nothing
in `build/abs-red/` records how the case inputs were made.

So the front-matter cuts in CUTS below were **reverse-engineered** by diffing the existing
artifacts against the corpus (exact line ranges, verified byte-identical), and they are
pinned here together with the corpus sha256 so the regeneration stays checkable.  They are
therefore *cut ranges keyed to two specific corpus revisions*, not a general algorithm —
that is the honest description of what could be recovered.

Note the two ranges are NOT symmetric between A and C: for A the blank line after the
`Keywords:` line is deleted, for C it is kept.  No uniform rule reproduces both, which is
itself evidence that the inputs were produced by hand-editing rather than by a script.

Usage
-----
    python tests/skills/make-abs-cases.py                 # write to a temp dir, then compare
    python tests/skills/make-abs-cases.py --out DIR       # write somewhere specific
    python tests/skills/make-abs-cases.py --quiet         # only the True/False table

Exit code is 0 only if every regenerated file is byte-identical to its reference copy.
"""
from __future__ import annotations

import argparse
import hashlib
import os
import re
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))          # tests/skills/ -> repo root

CORPUS_MD = {
    "A": "corpus/papers/md/2025美赛O奖论文/A/2501909.md",
    "C": "corpus/papers/md/2025美赛O奖论文/C/2505964.md",
}
CORPUS_PDF = {
    "A": "corpus/官方原题/2025/2025_MCM_Problem_A.pdf",
    "C": "corpus/官方原题/2025/2025_MCM_Problem_C.pdf",
}
# pdftotext argv tail; C needs -layout because its题面 is a two-column-ish table layout
PDFTOTEXT_ARGS = {"A": ["-enc", "UTF-8"], "C": ["-enc", "UTF-8", "-layout"]}

SHA256 = {
    "corpus/papers/md/2025美赛O奖论文/A/2501909.md":
        "80e5252f3e273881e06b7f555caf92e30d034fee03f010ddc8ced1acdaf6c9df",
    "corpus/papers/md/2025美赛O奖论文/C/2505964.md":
        "806948ed70d601ecbe7b39342c452a052e9d4268f090e7fdd515db789409abf4",
    "corpus/官方原题/2025/2025_MCM_Problem_A.pdf":
        "96c00a912be48be43ec5992669a707538e837eec79acc70931b36f50da2aec38",
    "corpus/官方原题/2025/2025_MCM_Problem_C.pdf":
        "e3d1dcd7c06ba457b288ae8426707adb209fedf6f0823dcda2ba16f994708bf7",
}

# 1-indexed inclusive line ranges deleted from the corpus .md.  None = "to EOF".
CUTS = {
    "A": [(1, 11), (14, 173)],
    "C": [(1, 11), (16, 46), (48, 186), (1248, None)],
}
# The paper's own Summary paragraph: (line of the `Summary` heading, line of the
# `Keywords:` line), 1-indexed.  The heading line itself is emitted literally as
# "Summary"; the slice that follows is corpus lines heading+1 .. last.
ABSTRACT = {"A": (14, 51), "C": (16, 46)}

RESIDUE = [
    re.compile(r"^<!-- page \d+ -->$"),
    re.compile(r"^Team # \d+$"),
    re.compile(r"^Page \d+ of \d+$"),
]

# --------------------------------------------------------------- Task-2 cuts
# (start, end, replacement)  1-indexed inclusive, on the GENERATED case-A-body.md.
# Ported verbatim from build/abs-red/make_partial.py (the throwaway that made the
# artifact); kept here so the partial is reproducible too.
PARTIAL_CUTS = [
    (652, 654, None),
    (745, 751, None),
    (779, 783, "If η < 0.05, we believe that we successfully determine the origin."),
    (805, 807, None),
    (825, 828, None),
    (849, 859, "Therefore, we obtain the method to estimate the the number of people using stairs\n"
               "frequency of multiple people in a typical day from the edge distribution of the measurement\n"
               "matrix Dmeasure\nx\n. "),
]

# ---------------------------------------------------------------- reference
# Where the byte-identity check looks for the reference copies.  build/abs-red/ is
# the original staging area (gitignored, may be gone); the in-repo copy under
# tests/skills/abs-cases/ is the durable one and has to be byte-identical to it.
REF_DIRS = [
    os.path.join(ROOT, "build", "abs-red"),
    os.path.join(ROOT, "tests", "skills", "abs-cases"),
]


def sha256_file(path: str) -> str:
    with open(path, "rb") as fh:
        return hashlib.sha256(fh.read()).hexdigest()


def read_text(path: str) -> str:
    """Read with newline='' so no line-ending translation happens anywhere."""
    with open(path, "r", encoding="utf-8", newline="") as fh:
        return fh.read()


def write_bytes(path: str, data: bytes) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as fh:
        fh.write(data)


def check_sources() -> None:
    bad = []
    for rel, want in SHA256.items():
        p = os.path.join(ROOT, rel)
        if not os.path.exists(p):
            bad.append("%s: MISSING" % rel)
        elif sha256_file(p) != want:
            bad.append("%s: sha256 mismatch (want %s, got %s)"
                       % (rel, want[:12], sha256_file(p)[:12]))
    if bad:
        sys.stderr.write("source check failed:\n  " + "\n  ".join(bad) + "\n")
        sys.exit(2)


def strip_body(letter: str, corpus: str) -> str:
    lines = corpus.replace("\x00", "").split("\n")
    keep = [True] * len(lines)
    for start, end in CUTS[letter]:
        end = len(lines) if end is None else end
        for i in range(start - 1, min(end, len(lines))):
            keep[i] = False
    out = []
    for i, ln in enumerate(lines):
        if not keep[i]:
            continue
        if any(r.match(ln) for r in RESIDUE):
            continue
        out.append(ln)
    collapsed, run = [], 0
    for ln in out:
        if ln.strip() == "":
            run += 1
            if run <= 2:
                collapsed.append(ln)
        else:
            run = 0
            collapsed.append(ln)
    while collapsed and collapsed[-1].strip() == "":
        collapsed.pop()
    return "\n".join(collapsed) + "\n"


def strip_abstract(letter: str, corpus: str) -> str:
    lines = corpus.replace("\x00", "").split("\n")
    a, b = ABSTRACT[letter]
    return "Summary\n" + "\n".join(lines[a:b]) + "\n"


def strip_partial(body: str) -> str:
    lines = body.split("\n")
    out, last = [], 1
    for start, end, repl in PARTIAL_CUTS:
        out.extend(lines[last - 1:start - 1])
        if repl is not None:
            out.extend(repl.split("\n"))
        last = end + 1
    out.extend(lines[last - 1:])
    return "\n".join(out)


def run_pdftotext(letter: str, tmp_pdf_dir: str) -> bytes:
    """pdftotext writes to a file; run it and read the bytes back."""
    src = os.path.join(ROOT, CORPUS_PDF[letter])
    dst = os.path.join(tmp_pdf_dir, "case-%s-problem.txt" % letter)
    cmd = ["pdftotext"] + PDFTOTEXT_ARGS[letter] + [src, dst]
    p = subprocess.run(cmd, capture_output=True, text=True, errors="replace")
    if p.returncode != 0 or not os.path.exists(dst):
        sys.stderr.write("pdftotext failed for %s: rc=%s\n%s\n"
                         % (letter, p.returncode, p.stderr))
        sys.exit(2)
    with open(dst, "rb") as fh:
        return fh.read()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    ap.add_argument("--out", default=None,
                    help="output directory (default: a fresh temp dir)")
    ap.add_argument("--quiet", action="store_true",
                    help="print only the byte-identity table")
    args = ap.parse_args()

    check_sources()

    out = args.out or tempfile.mkdtemp(prefix="abs-cases-")
    out = os.path.abspath(out)
    os.makedirs(out, exist_ok=True)

    produced = {}

    pdf_tmp = tempfile.mkdtemp(prefix="abs-cases-pdf-")
    for letter in ("A", "C"):
        produced["case-%s-problem.txt" % letter] = run_pdftotext(letter, pdf_tmp)

    for letter in ("A", "C"):
        corpus = read_text(os.path.join(ROOT, CORPUS_MD[letter]))
        body = strip_body(letter, corpus)
        produced["case-%s-body.md" % letter] = body.encode("utf-8")
        produced["case-%s-true-abstract.md" % letter] = \
            strip_abstract(letter, corpus).encode("utf-8")

    produced["case-A-body-partial.md"] = \
        strip_partial(produced["case-A-body.md"].decode("utf-8")).encode("utf-8")

    for name, data in produced.items():
        write_bytes(os.path.join(out, name), data)
        if not args.quiet:
            print("wrote %-26s %7d bytes" % (name, len(data)))
    if not args.quiet:
        print("\nout: %s\n" % out)

    # ------------------------------------------------------------ byte check
    refs = [d for d in REF_DIRS if os.path.isdir(d)]
    print("byte-identity check against the reference copies")
    if not refs:
        print("  no reference dir found (looked for %s) -- nothing to compare"
              % ", ".join(REF_DIRS))
        return 1
    all_same = True
    for ref in refs:
        origin = "staging (build/, gitignored)" if ref.endswith("abs-red") \
            else "in-repo copy (tests/skills/abs-cases/)"
        print("  [%s]" % origin)
        for name in sorted(produced):
            rp = os.path.join(ref, name)
            if not os.path.exists(rp):
                print("    %-26s REFERENCE MISSING" % name)
                all_same = False
                continue
            with open(rp, "rb") as fh:
                ref_bytes = fh.read()
            same = ref_bytes == produced[name]
            all_same = all_same and same
            print("    %-26s identical=%s" % (name, same))
            if not same:
                a, b = produced[name], ref_bytes
                first = next((i for i in range(min(len(a), len(b))) if a[i] != b[i]),
                             min(len(a), len(b)))
                print("        first difference at byte %d (ours %d bytes, ref %d bytes)"
                      % (first, len(a), len(b)))

    # artifacts are read-only inputs to this script; report only
    red_dir = os.path.join(ROOT, "tests", "skills", "abs-cases", "red")
    if os.path.isdir(red_dir):
        print("\nRED-stage artifacts (agent samples, NOT regenerated by this script):")
        for name in sorted(os.listdir(red_dir)):
            print("    %-26s %7d bytes" % (name, os.path.getsize(os.path.join(red_dir, name))))
    return 0 if all_same else 1


if __name__ == "__main__":
    sys.exit(main())
